In [3]:
#Import necessary Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import string
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, LSTM, Dropout, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping
import os
os.chdir("C://Hello/csv_file")

In [4]:
# load datasets 

df = pd.read_csv("IMDBmoviedataset.csv")
df.head()

,title.id,title.isAdult,title.canRateTitle.isRatable,title.originalTitleText.text,title.primaryImage.id,title.primaryImage.imageUrl,title.primaryImage.imageWidth,title.primaryImage.imageHeight,title.ratingsSummary.aggregateRating,title.ratingsSummary.topRanking,...,title.titleType.id,title.titleType.text,title.titleType.displayableProperty.value.plainText,title.titleType.categories,title.titleType.canHaveEpisodes,title.titleType.isSeries,title.titleType.isEpisode,title.series,title.ratingsSummary.topRanking.rank,country
0,tt28259207,False,True,Kill,rm671641857,https://m.media-amazon.com/images/M/MV5BZjI1Zj...,1080,1350,7.9,NaN,...,movie,Movie,NaN,"[{'id': 'movie', 'text': 'Movie', 'value': 'mo...",False,False,False,NaN,NaN,IN
1,tt27440937,False,True,Weapon,rm3727717121,https://m.media-amazon.com/images/M/MV5BMzIxMD...,820,1280,8.7,NaN,...,movie,Movie,NaN,"[{'id': 'movie', 'text': 'Movie', 'value': 'mo...",False,False,False,NaN,NaN,IN
2,tt23864864,False,True,Joram,rm4185347073,https://m.media-amazon.com/images/M/MV5BOWE4M2...,1000,1500,6.6,NaN,...,movie,Movie,NaN,"[{'id': 'movie', 'text': 'Movie', 'value': 'mo...",False,False,False,NaN,NaN,IN
3,tt11651796,False,True,AK vs AK,rm279368193,https://m.media-amazon.com/images/M/MV5BNDJkOT...,805,1200,6.9,NaN,...,movie,Movie,NaN,"[{'id': 'movie', 'text': 'Movie', 'value': 'mo...",False,False,False,NaN,NaN,IN
4,tt14479746,False,True,Thar,rm402464513,https://m.media-amazon.com/images/M/MV5BOWY1Nj...,1080,1078,6.1,NaN,...,movie,Movie,NaN,"[{'id': 'movie', 'text': 'Movie', 'value': 'mo...",False,False,False,NaN,NaN,IN

In [5]:
# Data exploration 
# Check for NULL Values
print(df.isnull().sum())

title.id                                                 0
title.isAdult                                            0
title.canRateTitle.isRatable                             0
title.originalTitleText.text                             0
title.primaryImage.id                                    0
title.primaryImage.imageUrl                              0
title.primaryImage.imageWidth                            0
title.primaryImage.imageHeight                           0
title.ratingsSummary.aggregateRating                     0
title.ratingsSummary.topRanking                        169
title.ratingsSummary.voteCount                           0
title.releaseYear.year                                   0
title.releaseYear.endYear                              169
title.titleEpisode                                     169
title.titleText.text                                     0
title.titleType.id                                       0
title.titleType.text                                     0
title.titleType.displayableProperty.value.plainText    165
title.titleType.categories                               0
title.titleType.canHaveEpisodes                          0
title.titleType.isSeries                                 0
title.titleType.isEpisode                                0
title.series                                           169
title.ratingsSummary.topRanking.rank                   107
country                                                  0
dtype: int64

In [11]:
# Data preprocessing
# Text cleaning function
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
def remove_stopwords(text):
    stop_words = set(stopwards.words('english'))
    words = text.split()
    return ' '.join([word for word in words if word not in stop_words])

def normalize_text(text):
    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+', '',text)#REmove URL
    text = re.sub(r"[^a-zA-Z\s]", ' ', text ) # Remove punctuation and non-alpha
    return text 

def clean_text(text):
    text = normalize_text(text)
    text = remove_stopwords(text)
    return text

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [12]:
df['cleaned_review'] = df['review'].apply(clean_text)

KeyError: 'review'